/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Build a cross-file symbol index from parse results.
 *
 * Collects all symbols, infers imports/exports, and computes file content hashes.
 */
export declare function buildIndex(parseResults: Array<NativeParseResult>): NativeSymbolIndex

/**
 * Run Louvain community detection on a graph.
 *
 * Takes a list of node IDs and edges, returns community assignments.
 * The algorithm optimizes modularity by iteratively moving nodes between
 * communities and then aggregating communities into super-nodes.
 */
export declare function detectCommunities(nodeIds: Array<string>, edges: Array<LouvainEdge>): LouvainResult

/** Map file extension to language ID. Returns null if the extension is not supported. */
export declare function extensionToLanguageId(extension: string): string | null

/** Initialize the parser (no-op — grammars are loaded on demand per parse call). */
export declare function initialize(): void

/** Check if a file extension maps to a supported language. */
export declare function isSupported(extension: string): boolean

/** A single node-to-community assignment. */
export interface LouvainCommunityAssignment {
  nodeId: string
  communityId: number
}

/** Input edge for the Louvain algorithm. */
export interface LouvainEdge {
  source: string
  target: string
  /** Optional edge weight (default: 1.0). */
  weight?: number
}

/** Result of Louvain community detection. */
export interface LouvainResult {
  /** Map of node ID to community ID. */
  communities: Array<LouvainCommunityAssignment>
  /** Final modularity score (0.0 to 1.0, higher = better partition). */
  modularity: number
  /** Number of communities detected. */
  numCommunities: number
}

/** A call expression found in source code. */
export interface NativeCallSite {
  /** Name of the function or method being called. */
  calleeName: string
  /** File where the call occurs. */
  filePath: string
  /** Line number of the call expression. */
  line: number
  /** Column number of the call expression start. */
  column: number
  /**
   * Column number of the actual function/method name (for precise navigation).
   * For `obj.method()`, this points to `method`, not `obj`.
   */
  nameColumn: number
}

/** A conditional or branching node in source code. */
export interface NativeConditionalNode {
  /** Type of conditional construct (if, switch, ternary, match). */
  kind: string
  /** File where the conditional occurs. */
  filePath: string
  /** Line number of the conditional (0-indexed). */
  line: number
  /** Column number of the conditional (0-indexed). */
  column: number
  /** End line of the conditional's body (0-indexed, from tree-sitter end_position). */
  endLine: number
  /** Number of branches in the conditional. */
  branches: number
  /** The condition expression text (e.g., "this.webviewReady", "cart.isEmpty()"). */
  conditionText: string
}

/** An export declaration extracted from a source file. */
export interface NativeExportEntry {
  /** Name of the exported binding. */
  name: string
  /** Kind of the exported symbol. */
  kind: string
  /** File containing the export declaration. */
  filePath: string
}

/** A file entry for batch parsing. */
export interface NativeFileEntry {
  /** Absolute path to the file. */
  filePath: string
  /** Language identifier for the file. */
  languageId: string
}

/** A file path and its content hash for cache invalidation. */
export interface NativeFileHash {
  /** Absolute path to the file. */
  filePath: string
  /** SHA-256 content hash of the file. */
  hash: string
}

/** An import declaration extracted from a source file. */
export interface NativeImportEntry {
  /** Module specifier or path being imported from. */
  source: string
  /** Names of imported bindings. */
  specifiers: Array<string>
  /** File containing the import declaration. */
  filePath: string
}

/** A flattened symbol entry in the cross-file index. */
export interface NativeIndexedSymbol {
  /** Simple name of the symbol. */
  name: string
  /** Fully qualified name (e.g., "MyClass.myMethod"). */
  qualifiedName: string
  /** Classification of the symbol (function, method, class, constructor, getter, setter). */
  kind: string
  /** File where the symbol is defined. */
  filePath: string
  /** Line number of the symbol definition (0-indexed). */
  line: number
  /** Column number of the symbol definition (0-indexed). */
  column: number
  /** Function/method signature string. */
  signature: string
  /** Start line of the symbol's body. */
  bodyStartLine: number
  /** End line of the symbol's body. */
  bodyEndLine: number
  /** Access visibility (public, private, protected, default). */
  visibility: string
  /** Language the symbol was parsed from. */
  languageId: string
}

/** An error encountered during file parsing. */
export interface NativeParseError {
  /** File where the error occurred. */
  filePath: string
  /** Line number of the error. */
  line: number
  /** Column number of the error. */
  column: number
  /** Human-readable error message. */
  message: string
}

/** Result of parsing a single source file. */
export interface NativeParseResult {
  /** Absolute path to the parsed file. */
  filePath: string
  /** Detected or overridden language of the file. */
  languageId: string
  /** Symbols (functions, methods, classes) extracted from the file. */
  symbols: Array<NativeSymbolEntry>
  /** Call expressions found in the file. */
  callSites: Array<NativeCallSite>
  /** Conditional/branching nodes found in the file. */
  conditionals: Array<NativeConditionalNode>
  /** Parse errors encountered during analysis. */
  errors: Array<NativeParseError>
}

/** A resolved call site linking a call expression to its definition. */
export interface NativeResolvedCall {
  /** Name of the function or method being called. */
  calleeName: string
  /** File where the call occurs. */
  filePath: string
  /** Line number of the call expression. */
  line: number
  /** Column number of the call expression. */
  column: number
  /** File where the definition is located (None if unresolved). */
  resolvedFilePath?: string
  /** Line number of the resolved definition. */
  resolvedLine?: number
  /** Resolved symbol name (may differ from callee_name for qualified names). */
  resolvedName?: string
  /** Whether the call was successfully resolved to a definition. */
  isResolved: boolean
}

/** A symbol (function, method, class) extracted from source code. */
export interface NativeSymbolEntry {
  /** Simple name of the symbol. */
  name: string
  /** Fully qualified name (e.g., "MyClass.myMethod"). */
  qualifiedName: string
  /** Classification of the symbol (function, method, class, constructor, getter, setter). */
  kind: string
  /** File where the symbol is defined. */
  filePath: string
  /** Line number of the symbol definition (0-indexed). */
  line: number
  /** Column number of the symbol definition (0-indexed). */
  column: number
  /** Function/method signature string. */
  signature: string
  /** Start line of the symbol's body. */
  bodyStartLine: number
  /** End line of the symbol's body. */
  bodyEndLine: number
  /** Access visibility (public, private, protected, default). */
  visibility: string
  /** Language the symbol was parsed from. */
  languageId: string
}

/** The complete cross-file symbol index. */
export interface NativeSymbolIndex {
  /** All symbols flattened from all parsed files. */
  symbols: Array<NativeIndexedSymbol>
  /** All import declarations. */
  imports: Array<NativeImportEntry>
  /** All export declarations. */
  exports: Array<NativeExportEntry>
  /** File path to content hash mapping. */
  fileHashes: Array<NativeFileHash>
}

/** Parse a single source file, extracting symbols, call sites, and conditionals. */
export declare function parseFile(filePath: string, languageId: string): NativeParseResult

/** Parse multiple files in parallel using rayon. */
export declare function parseFiles(files: Array<NativeFileEntry>): Array<NativeParseResult>

/** Health check function to verify the native addon is loaded. */
export declare function ping(): string

/**
 * Resolve call sites to their definitions using the symbol index.
 *
 * Resolution strategy:
 * 1. Exact name match in the same file → resolved
 * 2. Name match + import from that file → resolved
 * 3. Qualified name match (e.g., "MyClass.method") → resolved
 * 4. No match → unresolved
 */
export declare function resolveCalls(callSites: Array<NativeCallSite>, index: NativeSymbolIndex): Array<NativeResolvedCall>

/**
 * Incrementally update an existing index with changed file results.
 *
 * Removes all entries for changed files, then adds new entries from the changed results.
 */
export declare function updateIndex(existingIndex: NativeSymbolIndex, changedResults: Array<NativeParseResult>): NativeSymbolIndex
